# Generated by Django 4.2.16 on 2024-11-14 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('data', models.DateField()),
                ('description', models.CharField(max_length=500)),
                ('url', models.URLField(blank=True)),
            ],
        ),
    ]
